import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import AdobeFontsScript from './AdobeFontsScript';

import Navbar from './components/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <AdobeFontsScript />
      </head>
      <body className='font-sans'>
        <Navbar />
        <main className='p-12 prose max-w-none'>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
